# docker build .
# docker run --rm -ti <image id>

FROM alpine
COPY . /usr/src
RUN apk update && apk upgrade 
RUN apk add nano vim gcc nasm gdb 


FROM alpine
COPY ../pyImageSort /usr/src
RUN apk add nano vim gcc nasm gdb 
RUN apk add python3 py3-pip
# RUN python3 -m pip install --upgrade pip
RUN pip install numpy 
# RUN pip install scikit-learn
RUN pip install pytesseract
